import catchAsync from '../../utils/catchAsync.js';
import * as reportsService from './reportsServices.js';
import { attendanceDB } from '../../config/database.js';
import { reportQueue, redisConnection } from '../../config/queues.js';
import crypto from 'crypto';

export const previewReport = catchAsync(async (req, res) => {
    const isEmployee = req.user.user_type === "employee";
    const isUserReport = req.originalUrl.includes("/attendance/") || isEmployee;
    const targetUserId = isUserReport ? (req.user.user_id || req.user.id) : req.query.user_id;

    if (!isUserReport && req.user.user_type !== "admin" && req.user.user_type !== "hr") {
        return res.status(403).json({ ok: false, message: "Access denied" });
    }

    const { month, date, type, startDate, endDate, columns, dept_id, desg_id, shift_id } = req.query;
    const org_id = req.user.org_id;

    if (!type) {
        return res.status(400).json({ ok: false, message: "Report type is required" });
    }

    if (!startDate || !endDate) {
        if (["matrix_monthly", "attendance_matrix_monthly", "attendance_summary", "attendance_detailed"].includes(type) && !month) {
            return res.status(400).json({ ok: false, message: "Month is required" });
        }

        if (["matrix_weekly", "matrix_daily", "attendance_matrix_weekly"].includes(type) && !date) {
            return res.status(400).json({ ok: false, message: "Date is required" });
        }
    }

    const { startDate: resolvedStart, endDate: resolvedEnd } = reportsService.resolveDateRange({ type, month, date, startDate, endDate });
    const data = await reportsService.getPreviewData({ type, org_id, month, startDate: resolvedStart, endDate: resolvedEnd, targetUserId, columns, dept_id, desg_id, shift_id });

    res.json({ ok: true, data });
});


export const downloadReport = catchAsync(async (req, res) => {
    const { month, date, type, format = "xlsx", startDate, endDate, columns, dept_id, desg_id, shift_id } = req.query;

    const org_id = req.user.org_id;
    const isEmployee = req.user.user_type === "employee";
    const isUserReport = req.originalUrl.includes("/attendance/") || isEmployee;
    const targetUserId = isUserReport ? (req.user.user_id || req.user.id) : req.query.user_id;

    if (!isUserReport && req.user.user_type !== "admin" && req.user.user_type !== "hr") {
        return res.status(403).json({ ok: false, message: "Access denied" });
    }

    if (!type) {
        return res.status(400).json({ ok: false, message: "Report Type is required" });
    }

    if (!startDate || !endDate) {
        if (["matrix_monthly", "attendance_matrix_monthly", "attendance_summary", "attendance_detailed"].includes(type) && !month) {
            return res.status(400).json({ ok: false, message: "Month is required" });
        }

        if (["matrix_weekly", "matrix_daily", "attendance_matrix_weekly"].includes(type) && !date) {
            return res.status(400).json({ ok: false, message: "Date is required" });
        }
    }

    // Reports are generated by the background worker. Without Redis the job
    // cannot be queued (adding it would wait for a reconnect), so fail fast.
    if (redisConnection.status !== 'ready') {
        return res.status(503).json({ ok: false, message: "Report generation is temporarily unavailable. Please try again in a few minutes." });
    }

    const reportId = crypto.randomUUID();

    // 1. Write status entry to sys_generated_reports table
    await attendanceDB('sys_generated_reports').insert({
        report_id: reportId,
        user_id: req.user.user_id || req.user.id,
        org_id,
        report_type: type,
        format,
        status: 'pending'
    });

    const filename = `Report_${type}_${month || date || `${startDate}_to_${endDate}`}.${format}`;

    // 2. Add job to BullMQ (retries/backoff come from the queue defaults)
    try {
        await reportQueue.add('generate-report', {
            reportId,
            org_id,
            user_id: req.user.user_id || req.user.id,
            targetUserId,
            month,
            date,
            type,
            format,
            filename,
            startDate,
            endDate,
            columns: typeof columns === 'string' ? columns : JSON.stringify(columns),
            dept_id,
            desg_id,
            shift_id
        });
    } catch (err) {
        console.error(`Failed to queue report ${reportId}:`, err);
        await attendanceDB('sys_generated_reports')
            .where({ report_id: reportId })
            .update({ status: 'failed', error_message: 'Could not queue report job', updated_at: attendanceDB.fn.now() });
        return res.status(503).json({ ok: false, message: "Report generation is temporarily unavailable. Please try again in a few minutes." });
    }

    res.status(202).json({
        ok: true,
        message: "Report queued successfully",
        reportId
    });
});

export const getReportStatus = catchAsync(async (req, res) => {
    const { reportId } = req.params;
    const org_id = req.user.org_id;

    const report = await attendanceDB('sys_generated_reports')
        .where({ report_id: reportId, org_id })
        .first();

    if (!report) {
        return res.status(404).json({ ok: false, message: "Report not found" });
    }

    if (req.user.user_type !== "admin" && req.user.user_type !== "hr" && report.user_id !== (req.user.user_id || req.user.id)) {
        return res.status(403).json({ ok: false, message: "Access denied" });
    }

    res.json({ ok: true, data: report });
});